debug: true
# 10 - debug
log_level: 10
jupyterhub_url: 'http://192.168.0.31:30264'
jupyterhub_api_prefix: '/hub/api'
jupyterhub_api_token: 'ad6b8dc16f624b54a5b7d265f0744c97'
inactive_timeout: 1800 # in sec
cull_interval: 50 # cull every 180 sec
max_age: 86400 # in sec
cull_users: false
concurrency: 10
hash_key: 'mooplab-cull-timeout-hash'
redis_host: '192.168.0.31'
redis_port: 30078
redis_password: 'd2VsY29tZTEK' # set '' if you don't need password (will translate to None in python)